# Generated by Django 4.1 on 2022-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='total_shares',
            field=models.IntegerField(),
        ),
    ]
