# Generated by Django 4.1 on 2022-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='user',
        ),
    ]
