# Generated by Django 4.1 on 2022-09-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_items_total_shares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shares',
        ),
    ]
