# Generated by Django 4.1 on 2022-09-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_remove_shares_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='total_shares',
            field=models.IntegerField(null=True),
        ),
    ]
