# Generated by Django 4.1 on 2022-09-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_shares_total_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='user',
        ),
    ]
