# Generated by Django 4.1 on 2022-09-03 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_delete_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('total_shares', models.IntegerField()),
                ('price', models.FloatField(max_length=250)),
            ],
        ),
    ]
