# Generated by Django 4.1 on 2022-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shares',
        ),
    ]
